packages:
  - packages/**
  - examples/**
onlyBuiltDependencies:
  - esbuild
catalogs:
  intlify:
    '@intlify/shared': 11.1.3
    '@intlify/message-compiler': 11.1.3
    vue-i18n: 11.1.3
  vite:
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^6.3.5
  vue:
    vue: ^3.5.14
  webpack:
    ts-loader: ^9.5.2
    vue-loader: ^17.4.2
    webpack: ^5.99.8
catalog:
  '@types/node': ^22.15.19
  unbuild: ^3.5.0
  source-map-js: ^1.0.2
