packages:
  - packages/**
  - examples/**
catalogs:
  intlify:
    '@intlify/shared': ~11.4.2
    '@intlify/message-compiler': ~11.4.2
    vue-i18n: ~11.4.2
  vite:
    '@vitejs/plugin-vue': 5.2.4
    vite: 6.3.5
  rolldown-vite:
    vite: npm:rolldown-vite@latest
  vue:
    vue: ~3.5.34
  webpack:
    ts-loader: ~9.5.7
    vue-loader: ~17.4.2
    webpack: ~5.106.2
catalog:
  '@types/node': ^25.7.0
  unbuild: ^3.6.1
  source-map-js: ^1.2.1
allowBuilds:
  esbuild: true
  oxc-resolver: true
  unrs-resolver: true
overrides:
  vite: catalog:vite
  '@intlify/shared': ~11.4.2
  '@intlify/message-compiler': ~11.4.2
  '@intlify/core-base': ~11.4.2
  vue-i18n: ~11.4.2
  petite-vue-i18n: ~11.4.2
