packages:
  - packages/**
  - examples/**
catalogs:
  intlify:
    '@intlify/shared': ^11.1.12
    '@intlify/message-compiler': ^11.1.12
    vue-i18n: ^11.1.12
  vite:
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^6.3.6
  rolldown-vite:
    vite: npm:rolldown-vite@latest
  vue:
    vue: ^3.5.21
  webpack:
    ts-loader: ^9.5.4
    vue-loader: ^17.4.2
    webpack: ^5.101.3
catalog:
  '@types/node': ^22.18.4
  unbuild: ^3.6.1
  source-map-js: ^1.2.1
