packages:
  - packages/**
  - examples/**
onlyBuiltDependencies:
  - esbuild
catalogs:
  intlify:
    '@intlify/shared': next
    vue-i18n: next
  vite:
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^6.3.5
  vue:
    vue: ^3.5.14
  webpack:
    ts-loader: ^9.5.2
    vue-loader: ^17.0.0
    webpack: ^5.99.8
catalog:
  '@types/node': ^22.15.18
  unbuild: ^3.5.0
