export type { CodeGenOptions, CodeGenResult, DevEnv } from './codegen'
export { checkInstallPackage, getVueI18nVersion } from './deps'
export type { InstalledPackage } from './deps'
export { DynamicResourceError, generate as generateJavaScript } from './js'
export { generate as generateJSON } from './json'
export { generate as generateYAML } from './yaml'
